# Generated by Django 3.2.8 on 2022-03-25 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='iconoFontAwesome',
            new_name='icono_font_awesome',
        ),
    ]
