# Generated by Django 3.2.8 on 2022-03-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_iconofontawesome_contacto_icono_font_awesome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llave', models.TextField(unique=True)),
                ('valor', models.TextField()),
            ],
        ),
    ]
