# Generated by Django 3.2.8 on 2022-03-26 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_habilidad_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidad',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoriahabilidad'),
        ),
    ]
