# Generated by Django 3.2.8 on 2022-03-31 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_habilidad_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsoTecnologias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coletilla', models.CharField(max_length=100)),
                ('tecnologias', models.ManyToManyField(related_name='tecnologias', to='api.Tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='URLProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_ver', models.CharField(max_length=50)),
                ('url', models.TextField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='api.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='uso_tecnologias',
            field=models.ManyToManyField(related_name='usos_tecnologias', to='api.UsoTecnologias'),
        ),
    ]
