# Generated by Django 3.2.8 on 2022-03-31 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220330_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usotecnologias',
            name='coletilla',
            field=models.CharField(default='', max_length=100),
        ),
    ]
