# Generated by Django 3.2.8 on 2022-03-31 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_usotecnologias_coletilla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usotecnologias',
            old_name='coletilla',
            new_name='uso',
        ),
    ]
