# Generated by Django 3.2.8 on 2022-03-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_coletilla_usotecnologias_uso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usotecnologias',
            name='tecnologias',
            field=models.ManyToManyField(to='api.Tecnologia'),
        ),
    ]
