# Generated by Django 3.2.8 on 2022-03-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_usotecnologias_tecnologias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='uso_tecnologias',
            field=models.ManyToManyField(to='api.UsoTecnologias'),
        ),
    ]
