# Generated by Django 3.2.8 on 2022-03-31 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_proyecto_uso_tecnologias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='uso_tecnologias',
            new_name='usos_tecnologias',
        ),
    ]
