# Generated by Django 3.2.8 on 2022-04-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220402_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habilidad',
            name='categoria',
        ),
        migrations.AddField(
            model_name='categoriahabilidad',
            name='habilidades',
            field=models.ManyToManyField(to='api.Habilidad'),
        ),
    ]
