# Generated by Django 3.2.8 on 2022-04-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20220402_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencia',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
