# Generated by Django 3.2.8 on 2022-04-03 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20220402_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experiencia',
        ),
    ]
